stages:
  - update
  - install
  - deploy

# Use a Node.js image for the CI/CD pipeline
image: node:18

# Cache for dependencies to speed up the build process
cache:
  paths:
    - node_modules/

# Update code from the repository
update:
  stage: update
  script:
    - git pull origin main 
  only:
    - main

# Install dependencies
install:
  stage: install
  script:
    - npm install
